language: node_js

node_js:
  - "lts/*"

sudo: false

services:
  - xvfb

script:
  - yarn type-check
  - yarn lint
  - yarn test

notifications:
  email:
    on_failure: change

after_success:
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
